apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
spec:
  capacity:
    storage: 100Gi 
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /volume1/rhhknas19/ray/image-registry-storage 
    server: 192.168.35.19
  persistentVolumeReclaimPolicy: Recycle