apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0004
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas-nfs
  nfs:
    server: 192.168.35.19
    path: /volume1/rhhknas19/ray/pv0004